CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_01 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_01 data.start_idx=704 data.end_idx=779 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_01 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_01 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_01 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_03 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_03 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_03 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=804 data.end_idx=904 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=904 data.end_idx=1004 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04 data.start_idx=1004 data.end_idx=1104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_04 data.start_idx=304 data.end_idx=354 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_05 data.start_idx=3 data.end_idx=103 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_05 data.start_idx=103 data.end_idx=203 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_06 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_06 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_06 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_05 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_05 data.start_idx=404 data.end_idx=455 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=3 data.end_idx=103 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=103 data.end_idx=203 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=203 data.end_idx=303 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=303 data.end_idx=403 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=403 data.end_idx=503 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=503 data.end_idx=603 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=603 data.end_idx=703 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=703 data.end_idx=803 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05 data.start_idx=803 data.end_idx=853 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_06 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_06 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
ding echo "PROCESS: 50 / 1097 = 0.044667274384685506"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_06 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_06 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_06 data.start_idx=404 data.end_idx=525 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_06 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_06 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_06 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_06 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_06 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_04 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_04 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_04 data.start_idx=200 data.end_idx=250 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_05 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_05 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_05 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_05 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_05 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_05 data.start_idx=500 data.end_idx=550 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=800 data.end_idx=900 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=900 data.end_idx=1000 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03 data.start_idx=1000 data.end_idx=1051 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_04 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_04 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_04 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_04 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_04 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_04 data.start_idx=500 data.end_idx=550 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_04 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_04 data.start_idx=504 data.end_idx=603 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_05 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_05 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_04 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
ding echo "PROCESS: 100 / 1097 = 0.0902461257976299"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_01 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_01 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_01 data.start_idx=204 data.end_idx=354 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_02 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_02 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_02 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_02 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_02 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_02 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_02 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_02 data.start_idx=404 data.end_idx=455 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03 data.start_idx=804 data.end_idx=854 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_02 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_02 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_02 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_02 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_02 data.start_idx=404 data.end_idx=525 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_03 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_03 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_03 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_02 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_02 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_02 data.start_idx=200 data.end_idx=250 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_02 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_02 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_02 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_02 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_02 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_02 data.start_idx=500 data.end_idx=550 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
ding echo "PROCESS: 150 / 1097 = 0.1358249772105743"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=800 data.end_idx=900 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=900 data.end_idx=1000 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01 data.start_idx=1000 data.end_idx=1051 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_00 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_00 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_00 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_00 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_00 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_00 data.start_idx=500 data.end_idx=550 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_05 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_05 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_05 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_05 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_05 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_05 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_05 data.start_idx=600 data.end_idx=711 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_05 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_05 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_05 data.start_idx=504 data.end_idx=603 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_06 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_06 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_06 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_06 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_06 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_05 data.start_idx=3 data.end_idx=103 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_05 data.start_idx=103 data.end_idx=203 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_05 data.start_idx=203 data.end_idx=303 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_05 data.start_idx=303 data.end_idx=403 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_05 data.start_idx=403 data.end_idx=453 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_03 data.start_idx=204 data.end_idx=354 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_03 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_04 data.start_idx=404 data.end_idx=455 run_opt=True run_vis=False
ding echo "PROCESS: 200 / 1097 = 0.1814038286235187"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04 data.start_idx=804 data.end_idx=854 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_04 data.start_idx=404 data.end_idx=525 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_05 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_05 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_03 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_03 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_03 data.start_idx=200 data.end_idx=250 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_04 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_04 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_04 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_04 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_04 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_04 data.start_idx=500 data.end_idx=550 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=800 data.end_idx=900 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=900 data.end_idx=1000 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02 data.start_idx=1000 data.end_idx=1051 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_03 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_03 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_03 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_03 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_03 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_03 data.start_idx=500 data.end_idx=550 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
ding echo "PROCESS: 250 / 1097 = 0.22698268003646307"
# CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03 data.start_idx=704 data.end_idx=779 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_04 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=804 data.end_idx=904 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=904 data.end_idx=1004 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05 data.start_idx=1004 data.end_idx=1104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_05 data.start_idx=3 data.end_idx=103 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_05 data.start_idx=103 data.end_idx=203 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_05 data.start_idx=203 data.end_idx=353 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_00 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_00 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_00 data.start_idx=204 data.end_idx=254 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_00 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_00 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_00 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_00 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_00 data.start_idx=404 data.end_idx=503 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_01 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_01 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_01 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_01 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_01 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_01 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_01 data.start_idx=604 data.end_idx=654 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_01 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_01 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_01 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_01 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_01 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
ding echo "PROCESS: 300 / 1097 = 0.2725615314494075"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00 data.start_idx=804 data.end_idx=904 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00 data.start_idx=804 data.end_idx=854 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_00 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_00 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_00 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_00 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_00 data.start_idx=400 data.end_idx=450 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_00 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_00 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_00 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_00 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_00 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_00 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_00 data.start_idx=600 data.end_idx=750 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00 data.start_idx=800 data.end_idx=850 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
ding echo "PROCESS: 350 / 1097 = 0.31814038286235186"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04 data.start_idx=704 data.end_idx=779 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_05 data.start_idx=3 data.end_idx=103 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_05 data.start_idx=103 data.end_idx=203 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_05 data.start_idx=203 data.end_idx=303 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_05 data.start_idx=3 data.end_idx=103 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_05 data.start_idx=103 data.end_idx=203 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_05 data.start_idx=203 data.end_idx=303 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_05 data.start_idx=303 data.end_idx=403 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_05 data.start_idx=403 data.end_idx=453 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=804 data.end_idx=904 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=904 data.end_idx=1004 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06 data.start_idx=1004 data.end_idx=1104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_00 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_00 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_00 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_02 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_02 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_02 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_02 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_02 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_04 data.start_idx=204 data.end_idx=254 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_03 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_03 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_03 data.start_idx=404 data.end_idx=503 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_04 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_04 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_04 data.start_idx=604 data.end_idx=654 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_02 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_02 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_02 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_02 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_02 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
ding echo "PROCESS: 400 / 1097 = 0.3637192342752963"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01 data.start_idx=804 data.end_idx=904 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04 data.start_idx=804 data.end_idx=854 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_03 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_03 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_03 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_03 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_03 data.start_idx=400 data.end_idx=450 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_01 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_01 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_01 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_01 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_01 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_01 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_01 data.start_idx=600 data.end_idx=750 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01 data.start_idx=800 data.end_idx=850 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
ding echo "PROCESS: 450 / 1097 = 0.40929808568824066"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05 data.start_idx=704 data.end_idx=779 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_06 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_06 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_06 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_06 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_06 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_06 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_06 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_06 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=804 data.end_idx=904 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02 data.start_idx=904 data.end_idx=1004 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_03 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_03 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_03 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_03 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_03 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_03 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_05 data.start_idx=3 data.end_idx=103 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_05 data.start_idx=103 data.end_idx=203 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_05 data.start_idx=203 data.end_idx=253 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_04 data.start_idx=404 data.end_idx=503 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_05 data.start_idx=3 data.end_idx=103 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_05 data.start_idx=103 data.end_idx=203 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_05 data.start_idx=203 data.end_idx=303 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_05 data.start_idx=303 data.end_idx=403 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_05 data.start_idx=403 data.end_idx=503 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_05 data.start_idx=503 data.end_idx=603 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_05 data.start_idx=603 data.end_idx=653 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_04 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_04 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_04 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_04 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
ding echo "PROCESS: 500 / 1097 = 0.45487693710118504"
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_04 data.start_idx=404 data.end_idx=454 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02 data.start_idx=804 data.end_idx=904 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=204 data.end_idx=304 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=304 data.end_idx=404 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=404 data.end_idx=504 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=504 data.end_idx=604 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=604 data.end_idx=704 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=704 data.end_idx=804 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05 data.start_idx=804 data.end_idx=854 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_04 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_04 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_04 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_04 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_04 data.start_idx=400 data.end_idx=450 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_05 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_05 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_05 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_05 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_05 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_05 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_05 data.start_idx=600 data.end_idx=750 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=0 data.end_idx=100 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=100 data.end_idx=200 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=200 data.end_idx=300 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=300 data.end_idx=400 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=400 data.end_idx=500 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=500 data.end_idx=600 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=600 data.end_idx=700 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=700 data.end_idx=800 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04 data.start_idx=800 data.end_idx=850 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips1-cam_00 data.start_idx=4 data.end_idx=104 run_opt=True run_vis=False
CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips1-cam_00 data.start_idx=104 data.end_idx=204 run_opt=True run_vis=False
