ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_04  run_opt=False run_vis=False
# ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_009_sidebalancerun1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_pushup2-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_019_wipingchairs1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence2-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_019_wipingchairs1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_cooking2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips4-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_eating1-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips3-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_pushup2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_009_sidebalancerun1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips2-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_cooking2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_05  run_opt=False run_vis=False
# ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_cooking2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge2-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_eating1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_overfence2-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_009_sidebalancerun1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_pushup2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_pushup1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_cooking1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_cooking1-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge2-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_burpee2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips4-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_019_wipingchairs1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro2-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_019_wipingchairs1-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_sidebalancerun1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips4-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips1-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_sidebalancerun1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_009_sidebalancerun1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_pushup2-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_010_plankjack1-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro5-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_eating1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips3-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips4-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup1-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge2-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump1-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_017_burpeejump2-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_spray1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_mountainclimber2-cam_06  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_dips1-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_impro1-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_burpeejump2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_pushup2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_pushup1-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_00  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_lunge1-cam_01  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-LectureHall_021_plankjack1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge2-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_pushup2-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_dips2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_011_dips1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_012_lunge1-cam_03  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge2-cam_02  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_013_burpee4-cam_04  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge1-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-Gym_010_lunge2-cam_05  run_opt=False run_vis=False
ding CUDA_VISIBLE_DEVICES="1" python run_opt.py data=rich data.seq=test-ParkingLot2_009_overfence2-cam_00  run_opt=False run_vis=False